sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1q2w3e
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEgD1rptcWNb8GQg4Vu
    access-key-secret: q23DYTO9PVx5QrIJu4El58wI64lTzN
    bucket-name: web-kirika-tlias
